version: 2.1
orbs: 
  aws-s3: circleci/aws-s3@3.0.0

jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01

    steps:
      - checkout
      - run:
          name: Installing AWS CLI
          command: |
            sudo apt-get update
            sudo apt install python3-pip
            sudo pip3 install awsebcli --upgrade
      - run: cd ./app && npm install && npm run build
       - aws-s3/sync:
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400"
          aws-access-key-id: AKIA2VTWYU5VKW55IVHH
          aws-region: us-east-1
          aws-secret-access-key: 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
          from: bucket
          to: 's3://circleci-build-deploy-pavan'
      - aws-s3/copy:
          arguments: '--dryrun'
          from: bucket/build_asset.txt
          to: 's3:/circleci-build-deploy-pavan'
      - persist_to_workspace:
          root: .
          paths:
            - .
  test:
    machine:
      image: ubuntu-2004:202010-01

    steps:
      - attach_workspace:
          at: .
      - checkout
      - run: cd ./app && npm run test
      - persist_to_workspace:
          root: .
          paths:
            - .
  deploy:
    machine:
        image: ubuntu-2004:202010-01

    steps:
      - attach_workspace:
          at: .
      - checkout
      - run: aws s3 sync ./app/build s3://circleci-build-deploy-pavan
    

workflows:
  build_test_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
